#!/usr/bin/env node

/**
 * Persona Probe CLI
 *
 * Usage:
 *   persona-probe init --name "New User" --output personas/new-user.yml
 *   persona-probe run --persona personas/new-user.yml --url https://app.example.com
 *   persona-probe run --personas personas/ --url https://app.example.com
 *   persona-probe check --reports reports/ --min-readiness 60
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "fs";
import { join, basename, extname } from "path";
import { parse as parseYaml } from "yaml";
import type { PersonaDefinition, ProbeResult, ProbeConfig } from "./schema.js";

function loadPersona(path: string): PersonaDefinition {
  const content = readFileSync(path, "utf-8");
  return parseYaml(content) as PersonaDefinition;
}

function loadConfig(): ProbeConfig {
  const configPaths = [".persona-probe.yml", ".persona-probe.yaml"];
  for (const p of configPaths) {
    if (existsSync(p)) {
      return parseYaml(readFileSync(p, "utf-8")) as ProbeConfig;
    }
  }

  return {
    provider: (process.env.PERSONA_PROBE_PROVIDER as "anthropic" | "openai") || "anthropic",
    model: process.env.PERSONA_PROBE_MODEL,
    api_key: process.env.PERSONA_PROBE_API_KEY,
    report_dir: "./reports",
    screenshot_dir: "./screenshots",
  };
}

function generateInitTemplate(name: string): string {
  return `# Persona: ${name}
# Generated by persona-probe init

name: ${name}
title: "Job Title"
experience: "Describe their experience level"
technical_comfort: "low | moderate | high"

context: |
  Describe the persona's situation. What brought them to the app?
  What pressure are they under? What do they already know?

goals:
  - First goal
  - Second goal
  - Third goal

scenarios:
  - name: First Impressions
    description: Land on the app and orient
    success: Can understand the app's purpose within 5 minutes

  - name: Core Workflow
    description: Complete the primary use case
    success: Successfully completes the workflow

evaluation_criteria:
  - name: Onboarding Clarity
    weight: critical
    question: Did I understand what to do without help?

  - name: Speed to Value
    weight: high
    question: How quickly did I see something useful?

voice: |
  Speak as this persona would. Include example quotes:
  "Example of how they'd express frustration"
  "Example of how they'd express satisfaction"

critical_bug_protocol:
  stop_on:
    - page_fails_to_render
    - data_not_loading
  continue_on:
    - minor_ui_issues
    - slow_loading
`;
}

async function runProbe(persona: PersonaDefinition, url: string, config: ProbeConfig): Promise<ProbeResult> {
  // This is the integration point where the AI model + browser automation runs.
  // In the full implementation, this launches Playwright, sends the persona
  // definition to the AI model, and collects structured results.
  //
  // For now, this prints the probe configuration and returns a placeholder.
  console.log(`\nProbing ${url} as ${persona.name} (${persona.title})`);
  console.log(`Provider: ${config.provider}`);
  console.log(`Scenarios: ${persona.scenarios.length}`);
  console.log(`Criteria: ${persona.evaluation_criteria.length}`);
  console.log("");

  // TODO: Implement browser automation integration
  // 1. Launch Playwright browser
  // 2. Build prompt from persona definition
  // 3. Send to AI model with browser control tools
  // 4. Collect structured results
  // 5. Generate markdown report

  throw new Error(
    "Browser automation not yet implemented. " +
    "See README.md for the planned architecture. " +
    "Contributions welcome!"
  );
}

function checkReports(reportDir: string, minReadiness: number): boolean {
  const files = readdirSync(reportDir).filter((f) => f.endsWith(".json"));
  let allPass = true;

  for (const file of files) {
    const content = readFileSync(join(reportDir, file), "utf-8");
    const result = JSON.parse(content) as ProbeResult;

    const status = result.readiness_pct >= minReadiness ? "PASS" : "FAIL";
    console.log(`${status}: ${result.persona} - ${result.readiness_pct}% readiness`);

    if (result.readiness_pct < minReadiness) {
      allPass = false;
    }

    if (result.critical_bugs) {
      console.log(`  CRITICAL BUGS detected for ${result.persona}`);
      allPass = false;
    }
  }

  return allPass;
}

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "--help" || command === "-h") {
    console.log(`persona-probe - AI persona testing framework

Commands:
  init    Create a new persona template
  run     Run a persona probe against a URL
  check   Check probe reports against readiness threshold

Examples:
  persona-probe init --name "New User" --output personas/new-user.yml
  persona-probe run --persona personas/new-user.yml --url https://app.example.com
  persona-probe check --reports reports/ --min-readiness 60
`);
    process.exit(0);
  }

  if (command === "init") {
    const nameIdx = args.indexOf("--name");
    const outputIdx = args.indexOf("--output");
    const name = nameIdx >= 0 ? args[nameIdx + 1] : "New User";
    const output = outputIdx >= 0 ? args[outputIdx + 1] : `personas/${name.toLowerCase().replace(/\s+/g, "-")}.yml`;

    const dir = join(output, "..");
    mkdirSync(dir, { recursive: true });
    writeFileSync(output, generateInitTemplate(name));
    console.log(`Created persona template: ${output}`);
    process.exit(0);
  }

  if (command === "run") {
    const config = loadConfig();
    const urlIdx = args.indexOf("--url");
    const url = urlIdx >= 0 ? args[urlIdx + 1] : undefined;

    if (!url) {
      console.error("Error: --url is required");
      process.exit(1);
    }

    const personaIdx = args.indexOf("--persona");
    const personasIdx = args.indexOf("--personas");

    const personaPaths: string[] = [];

    if (personaIdx >= 0) {
      personaPaths.push(args[personaIdx + 1]);
    }

    if (personasIdx >= 0) {
      const dir = args[personasIdx + 1];
      const files = readdirSync(dir).filter((f) => [".yml", ".yaml"].includes(extname(f)));
      personaPaths.push(...files.map((f) => join(dir, f)));
    }

    if (personaPaths.length === 0) {
      console.error("Error: --persona or --personas is required");
      process.exit(1);
    }

    for (const path of personaPaths) {
      const persona = loadPersona(path);
      try {
        await runProbe(persona, url, config);
      } catch (e) {
        console.error(`Error probing as ${persona.name}: ${(e as Error).message}`);
      }
    }
  }

  if (command === "check") {
    const reportsIdx = args.indexOf("--reports");
    const minIdx = args.indexOf("--min-readiness");
    const reportDir = reportsIdx >= 0 ? args[reportsIdx + 1] : "reports";
    const minReadiness = minIdx >= 0 ? parseInt(args[minIdx + 1]) : 60;

    const pass = checkReports(reportDir, minReadiness);
    process.exit(pass ? 0 : 1);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
