#!/usr/bin/env node

/**
 * Persona Testing CLI
 *
 * Usage:
 *   persona-testing init --name "New User" --output personas/new-user.yml
 *   persona-testing run --persona personas/new-user.yml --url https://app.example.com
 *   persona-testing run --personas personas/ --url https://app.example.com
 *   persona-testing check --reports reports/ --min-readiness 60
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "fs";
import { join, extname } from "path";
import { parse as parseYaml } from "yaml";
import type { PersonaDefinition, ProbeResult, ProbeConfig } from "./schema.js";
import { PlaywrightBridge } from "./tools.js";
import { buildSystemPrompt, buildUserMessage } from "./prompt.js";
import { createProvider } from "./loop.js";
import { parseAssessment } from "./parser.js";
import { saveReport, slugify } from "./reporter.js";

function loadPersona(path: string): PersonaDefinition {
  const content = readFileSync(path, "utf-8");
  return parseYaml(content) as PersonaDefinition;
}

function loadConfig(): ProbeConfig {
  const configPaths = [".persona-testing.yml", ".persona-testing.yaml"];
  for (const p of configPaths) {
    if (existsSync(p)) {
      return parseYaml(readFileSync(p, "utf-8")) as ProbeConfig;
    }
  }

  return {
    provider: (process.env.PERSONA_TESTING_PROVIDER as "anthropic" | "openai") || "anthropic",
    model: process.env.PERSONA_TESTING_MODEL,
    api_key: process.env.PERSONA_TESTING_API_KEY,
    report_dir: "./reports",
    screenshot_dir: "./screenshots",
  };
}

function generateInitTemplate(name: string): string {
  return `# Persona: ${name}
# Generated by persona-testing init

name: ${name}
title: "Job Title"
experience: "Describe their experience level"
technical_comfort: "low | moderate | high"

context: |
  Describe the persona's situation. What brought them to the app?
  What pressure are they under? What do they already know?

goals:
  - First goal
  - Second goal
  - Third goal

scenarios:
  - name: First Impressions
    description: Land on the app and orient
    success: Can understand the app's purpose within 5 minutes

  - name: Core Workflow
    description: Complete the primary use case
    success: Successfully completes the workflow

evaluation_criteria:
  - name: Onboarding Clarity
    weight: critical
    question: Did I understand what to do without help?

  - name: Speed to Value
    weight: high
    question: How quickly did I see something useful?

voice: |
  Speak as this persona would. Include example quotes:
  "Example of how they'd express frustration"
  "Example of how they'd express satisfaction"

critical_bug_protocol:
  stop_on:
    - page_fails_to_render
    - data_not_loading
  continue_on:
    - minor_ui_issues
    - slow_loading
`;
}

function resolveApiKey(config: ProbeConfig): string {
  if (config.api_key) return config.api_key;

  // Fall back to standard env vars
  if (config.provider === "anthropic") {
    const key = process.env.ANTHROPIC_API_KEY;
    if (key) return key;
  }
  if (config.provider === "openai") {
    const key = process.env.OPENAI_API_KEY;
    if (key) return key;
  }

  console.error(
    `Error: No API key found. Set PERSONA_TESTING_API_KEY, ` +
      `${config.provider === "anthropic" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY"}, ` +
      `or add api_key to .persona-testing.yml`,
  );
  process.exit(1);
}

async function runProbe(
  persona: PersonaDefinition,
  url: string,
  config: ProbeConfig,
): Promise<ProbeResult> {
  const personaSlug = slugify(persona.name);
  const screenshotDir = config.screenshot_dir || "./screenshots";
  const reportDir = config.report_dir || "./reports";

  console.log(`\nTesting ${url} as ${persona.name} (${persona.title})`);
  console.log(`Provider: ${config.provider}`);
  console.log(`Scenarios: ${persona.scenarios.length}`);
  console.log(`Criteria: ${persona.evaluation_criteria.length}`);

  // 1. Resolve API key before launching browser
  const apiKey = resolveApiKey(config);

  // 2. Launch browser
  let chromium: any;
  try {
    const pw = await import("playwright");
    chromium = pw.chromium;
  } catch {
    console.error(
      "Error: Playwright not found. Install it with:\n" +
        "  npm install playwright\n" +
        "  npx playwright install chromium",
    );
    process.exit(1);
  }

  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1280, height: 720 },
  });
  const page = await context.newPage();

  try {
    // 3. Build bridge
    const bridge = new PlaywrightBridge(page, { screenshotDir, personaSlug });

    // 4. Build provider
    const provider = createProvider(config.provider, {
      apiKey,
      model: config.model,
      maxIterations: config.max_iterations,
    });

    // 5. Build prompt
    const systemPrompt = buildSystemPrompt(persona, url);
    const userMessage = buildUserMessage(url);

    // 6. Run the AI loop
    console.log("Starting AI evaluation loop...\n");
    const loopResult = await provider.run(systemPrompt, userMessage, bridge);

    console.log(
      `\nLoop completed: ${loopResult.iterations} iterations, ` +
        `${loopResult.inputTokens} input / ${loopResult.outputTokens} output tokens`,
    );

    // 7. Parse result
    const probeResult = parseAssessment(loopResult.text, persona.name, url);
    probeResult.screenshots = bridge.screenshots;

    // 8. Save reports
    const { jsonPath, mdPath } = saveReport(probeResult, reportDir);
    probeResult.report_path = mdPath;

    console.log(`\nResults:`);
    console.log(`  Readiness: ${probeResult.readiness_pct}%`);
    console.log(`  Critical bugs: ${probeResult.critical_bugs ? "YES" : "None"}`);
    console.log(`  Items: ${probeResult.items.length}`);
    console.log(`  Screenshots: ${probeResult.screenshots.length}`);
    console.log(`  Reports: ${jsonPath}, ${mdPath}`);

    return probeResult;
  } finally {
    await browser.close();
  }
}

function checkReports(reportDir: string, minReadiness: number): boolean {
  if (!existsSync(reportDir)) {
    console.error(`Error: Report directory not found: ${reportDir}`);
    return false;
  }

  const files = readdirSync(reportDir).filter((f: string) => f.endsWith(".json"));

  if (files.length === 0) {
    console.error(`No report files found in ${reportDir}`);
    return false;
  }

  let allPass = true;

  for (const file of files) {
    const content = readFileSync(join(reportDir, file), "utf-8");
    const result = JSON.parse(content) as ProbeResult;

    const status = result.readiness_pct >= minReadiness ? "PASS" : "FAIL";
    console.log(`${status}: ${result.persona} - ${result.readiness_pct}% readiness`);

    if (result.readiness_pct < minReadiness) {
      allPass = false;
    }

    if (result.critical_bugs) {
      console.log(`  CRITICAL BUGS detected for ${result.persona}`);
      allPass = false;
    }
  }

  return allPass;
}

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "--help" || command === "-h") {
    console.log(`persona-testing - AI persona testing framework

Commands:
  init    Create a new persona template
  run     Run a persona test against a URL
  check   Check test reports against readiness threshold

Examples:
  persona-testing init --name "New User" --output personas/new-user.yml
  persona-testing run --persona personas/new-user.yml --url https://app.example.com
  persona-testing check --reports reports/ --min-readiness 60

Environment:
  PERSONA_TESTING_PROVIDER   anthropic (default) or openai
  PERSONA_TESTING_MODEL      Model name override
  PERSONA_TESTING_API_KEY    API key (also reads ANTHROPIC_API_KEY / OPENAI_API_KEY)

Config file:
  .persona-testing.yml in the current directory
`);
    process.exit(0);
  }

  if (command === "init") {
    const nameIdx = args.indexOf("--name");
    const outputIdx = args.indexOf("--output");
    const name = nameIdx >= 0 ? args[nameIdx + 1] : "New User";
    const output = outputIdx >= 0 ? args[outputIdx + 1] : `personas/${name.toLowerCase().replace(/\s+/g, "-")}.yml`;

    const dir = join(output, "..");
    mkdirSync(dir, { recursive: true });
    writeFileSync(output, generateInitTemplate(name));
    console.log(`Created persona template: ${output}`);
    process.exit(0);
  }

  if (command === "run") {
    const config = loadConfig();
    const urlIdx = args.indexOf("--url");
    const url = urlIdx >= 0 ? args[urlIdx + 1] : undefined;

    if (!url) {
      console.error("Error: --url is required");
      process.exit(1);
    }

    const personaIdx = args.indexOf("--persona");
    const personasIdx = args.indexOf("--personas");

    const personaPaths: string[] = [];

    if (personaIdx >= 0) {
      personaPaths.push(args[personaIdx + 1]);
    }

    if (personasIdx >= 0) {
      const dir = args[personasIdx + 1];
      const files = readdirSync(dir).filter((f: string) => [".yml", ".yaml"].includes(extname(f)));
      personaPaths.push(...files.map((f: string) => join(dir, f)));
    }

    if (personaPaths.length === 0) {
      console.error("Error: --persona or --personas is required");
      process.exit(1);
    }

    let hasFailure = false;
    for (const path of personaPaths) {
      const persona = loadPersona(path);
      try {
        await runProbe(persona, url, config);
      } catch (e) {
        console.error(`Error testing as ${persona.name}: ${(e as Error).message}`);
        hasFailure = true;
      }
    }

    if (hasFailure) process.exit(1);
  }

  if (command === "check") {
    const reportsIdx = args.indexOf("--reports");
    const minIdx = args.indexOf("--min-readiness");
    const reportDir = reportsIdx >= 0 ? args[reportsIdx + 1] : "reports";
    const minReadiness = minIdx >= 0 ? parseInt(args[minIdx + 1]) : 60;

    const pass = checkReports(reportDir, minReadiness);
    process.exit(pass ? 0 : 1);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
